<?php

function ubc_add_to_calendar_preprocess_node(&$variables) {

    if ($variables['node']->getType() == 'ubc_event') {

    	$nid = $variables['node']->id();
    	$node = node_load($nid);

    	$google_cal_link = ubc_add_to_calendar_addToGoogleCal($node);
			$variables['content']['google_cal_link'] = array('#markup' => $google_cal_link);

			$ical_link = ubc_add_to_calendar_addToICal($node);
			$variables['content']['ical_link'] = array('#markup' => $ical_link);
			$variables['content']['outlook_link'] = array('#markup' => $ical_link);
    }
}

function ubc_add_to_calendar_addToICal(&$node) {

	if(!isset($node->title)) {
		return null;
	}

	$title = $node->getTitle();

	$details = $node->get('body')->value;
	$details = strip_tags($details);

	$location = $node->get('field_event_location')->getValue();
	$location = $location[0]['address_line1'].', '.$location[0]['address_line2'].', '.$location[0]['locality'].', '.$location[0]['administrative_area'].', '.$location[0]['postal_code'].', '.$location[0]['country_code'];

	$dates = $node->get('field_event_date')->getValue();

	$start_date = $dates[0]['value'];
	$startDateTime = new DateTime($start_date);
	$start_date = $startDateTime->format('Ymd').'T'.$startDateTime->format('His').'Z';

	$end_date = $dates[0]['end_value'];
	$endDateTime = new DateTime($end_date);
	$end_date = $endDateTime->format('Ymd').'T'.$endDateTime->format('His').'Z';

	return 'data:text/calendar;charset=utf8,BEGIN:VCALENDAR%0AVERSION:2.0%0ABEGIN:VEVENT%0ADTSTART:'.$start_date.'%0ADTEND:'.$end_date.'%0ASUMMARY:'.$title.'%0ADESCRIPTION:'.$details.'%0ALOCATION:'.$location.'%0AEND:VEVENT%0AEND:VCALENDAR';

}


function ubc_add_to_calendar_addToGoogleCal(&$node) {

	if(!isset($node->title)) {
		return null;
	}

	$title = urlencode($node->getTitle());

	$dates = $node->get('field_event_date')->getValue();
	if(isset($dates[0]['value'])) {

		$start_date = $dates[0]['value'];
		$userTimezone = new DateTimeZone(drupal_get_user_timezone());
		$gmtTimezone = new DateTimeZone('GMT');
		$startDateTime = new DateTime($start_date, $gmtTimezone);
		$offset = $userTimezone->getOffset($startDateTime);
		$startInterval = DateInterval::createFromDateString((string)$offset . 'seconds');
		$startDateTime->add($startInterval);
		$start_date = $startDateTime->format('Ymd').'T'.$startDateTime->format('His');
  	$date = $start_date;

  	if(isset($dates[0]['end_value'])) {
  		$end_date = $dates[0]['end_value'];
			$endDateTime = new DateTime($end_date, $gmtTimezone);
			$offset = $userTimezone->getOffset($endDateTime);
			$endInterval = DateInterval::createFromDateString((string)$offset . 'seconds');
			$endDateTime->add($endInterval);
			$end_date = $endDateTime->format('Ymd').'T'.$endDateTime->format('His');
    	$date = $start_date .'/'.$end_date;
  	}
  	$dates = '&dates='.$date;
	}
	else {
		$dates = '';
	}

	$details = $node->get('body')->value;
	$details = urlencode(strip_tags($details));
	$details = '&details='.$details;

	$location = $node->get('field_event_location')->getValue();
	$location = $location[0]['address_line1'].', '.$location[0]['address_line2'].', '.$location[0]['locality'].', '.$location[0]['administrative_area'].', '.$location[0]['postal_code'].', '.$location[0]['country_code'];
	$location = '&location='.urlencode($location);

	return 'https://www.google.com/calendar/render?action=TEMPLATE&text='.$title.$dates.'&ctz=America/Vancouver'.$details.$location.'&sf=true&output=xml';
}
